export const FETCH_NAMEPAGE_START = "FETCH_NAMEPAGE_START";
export const FETCH_NAMEPAGE_SUCCESS = "FETCH_NAMEPAGE_SUCCESS";
export const FETCH_NAMEPAGE_FAIL = "FETCH_NAMEPAGE_FAIL";
export const INIT_FETCH_NAMEPAGE = "INIT_FETCH_NAMEPAGE";